cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  emails:
    a@gmail.com:
      compliance_message: true
      compliance_statut: false
      logged_in: false
      password: $2b$12$kvzlZort0..Ki5Y0KdB4guD9dmi6.xloES4J8ju7VflyB1xaWB9P2
    aaa@gmail.com:
      logged_in: false
      password: $2b$12$kDQVLyiIuVcTZMNSTCShKeC4uAQualwPBsOR8nNg6HOiJ3GcouDgi
    aza@gmail.com:
      compliance_message: true
      compliance_statut: true
      logged_in: false
      password: $2b$12$.3KFOOvm0.Cw3NMYafoMuuAoX7x.SaJBW2G6N.Anpx/9COWKjJ8a6
    b@gmail.com:
      logged_in: false
      password: $2b$12$H.Wxlm5IMMrxAwyuBgI6j.BtDkumUQuxvbjRi4TBsD8SNZ0upgHxu
    jsmith@gmail.com:
      logged_in: false
      password: $2b$12$06aKBOXstb17GpPWAZBEvuMVY67CVgh1pinKeD3ZukUKwDJ6o6gje
    rbriggs@gmail.com:
      logged_in: false
      password: $2b$12$K0YPSaOwoVvX2tZVILUtpeJScVrjhMspBnzJKT1XSvPI65MEYJcHO
    t@gmail.com:
      logged_in: false
      password: $2b$12$Y5dSDUGohYOTTwQx9dh/oOWpTDOnA2R3TWSLN/1r8XEeVfYwSb3Ee
    test@gmail.com:
      logged_in: false
      password: $2b$12$J6Ir95fed8EsjF/eCws0ReLi7zHMl4y/OsWcBicBLEzW.Brf2bUZq
    z@gmail.com:
      logged_in: false
      password: $2b$12$Ocx.OFnAjbvq83HN1ZmcN..19ZMLV2mrYtoYw0GuCM6l6B7zMD3SW
preauthorized:
  emails:
  - melsby@gmail.com
